### ISSUE TITLE
production

### ISSUE THREAD

**Issue by empereira** [Githubhat/freeradius-k8s#1]
hello @Githubhat,

Have you been using your deployment in production? Are you using metallb for LB?

**Comment by Githubhat** [comment]
We are using production along with lb.

**Comment by empereira** [comment]
What kind of auth do you use freeradius with? sql, ntlm, active directory, etc?

**Comment by Githubhat** [comment]
Local database of freeradiys

**Comment by empereira** [comment]
Ok. Thanks!!!
